services:
  jmeter:
    image: alpine
    default: true
    checkout: true

    commands:
      build:
        - apk add --no-cache openjdk11 wget bash
        - wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
        - tar -xzf apache-jmeter-5.6.3.tgz

      start:
        - echo "JMeter pronto"
