services:
  app:
    image: tugboatqa/ubuntu:22.04

    commands:
      build:
        - apt-get update
        - apt-get install -y git openjdk-17-jre wget unzip apache2

        # baixar jmeter
        - wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz

        # extrair
        - tar -xzf apache-jmeter-5.6.3.tgz

        # VER O NOME REAL DA PASTA
        - ls -l

        # testar direto da pasta (SEM MOVER)
        - ./apache-jmeter-5.6.3/bin/jmeter -v

      init:
        # criar pasta
        - rm -rf /var/lib/app
        - mkdir -p /var/lib/app

        # baixar jmx
        - wget https://raw.githubusercontent.com/natanaelgsneto/JMETER/main/secao6_ambiente_completo/pronto.jmx -O /var/lib/app/pronto.jmx

        # rodar teste DIRETO da pasta
        - ./apache-jmeter-5.6.3/bin/jmeter -n -t /var/lib/app/pronto.jmx -l /var/lib/app/resultado.jtl

        # gerar relatório
        - ./apache-jmeter-5.6.3/bin/jmeter -g /var/lib/app/resultado.jtl -o /var/lib/app/relatorio

        # publicar
        - rm -rf /var/www/html/*
        - cp -r /var/lib/app/relatorio/* /var/www/html/

        # subir apache
        - service apache2 start
